# Generated by Django 5.0.4 on 2024-05-06 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alert_types',
            fields=[
                ('alert_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_name', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('camera_name', models.CharField(blank=True, max_length=100, null=True)),
                ('area_id', models.IntegerField()),
                ('tank_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('area', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='camera_alerts',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.alert_types')),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.camera')),
            ],
        ),
        migrations.CreateModel(
            name='camera_settings',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateField(auto_now=True)),
                ('alert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.camera_alerts')),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.camera')),
            ],
        ),
        migrations.CreateModel(
            name='capture_video',
            fields=[
                ('captured_video_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('url', models.FileField(upload_to='video')),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.camera')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='guard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.guard'),
        ),
    ]
