# Generated by Django 4.2.12 on 2024-05-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera_settings',
            name='alert_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.alert_types'),
        ),
    ]
