# Generated by Django 4.2.12 on 2024-05-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_camera_settings_alert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_types',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert_types',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='camera_alerts',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
