# Generated by Django 4.2.13 on 2024-06-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_alert_types_date_alter_alert_types_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera_alerts',
            name='alert_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='camera_alerts',
            name='camera_id',
            field=models.CharField(max_length=50),
        ),
    ]
