# Generated by Django 4.2.13 on 2024-06-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_camera_alerts_alert_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera_alerts',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
